name = "pages-config-file"
compatibility_date = "2020-02-03"
pages_build_output_dir = "public"

[[durable_objects.bindings]]
name = "DO"
class_name = "Counter"
script_name = "testing"
environment = "production"
