name = "pages-config-file"
pages_build_output_dir = "public"

compatibility_date = "2024-02-13"
compatibility_flags = ["nodejs_compat"]

  [vars]
  TEST_JSON = """
{
json: "value"
}"""
  TEST_PLAINTEXT = "PLAINTEXT"
  VAR1 = "holiday-prod"
VAR2 = "celebrate-prod"
VAR3 = "another-var-prod"


  [[kv_namespaces]]
  id = "01962077d09242c5b0978a12bccaa5ed"
  binding = "KV"


[[durable_objects.bindings]]
name = "DO"
class_name = "Counter"
script_name = "testing"

  [[d1_databases]]
  database_id = "16678423-f19c-4a82-a3c1-161345dcfefe"
  binding = "D1"
  database_name = "D1"


  [[r2_buckets]]
  bucket_name = "images"
  binding = "R2"
  
  [[services]]
  binding = "SERVICE"
  service = "no-bundle-import"
  environment = "production"

  
[[queues.producers]]
binding = "Q"
queue = "test"


  [[analytics_engine_datasets]]
  binding = "AE"
  dataset = "data"
