name = "pages-config-file"
pages_build_output_dir = "public"

compatibility_date = "2024-02-13"
compatibility_flags = ["nodejs_compat"]

  [vars]
  TEST_JSON = """
{
json: "value"
}"""
  TEST_PLAINTEXT = "PLAINTEXT"
  VAR1 = "holiday-prod"
VAR2 = "celebrate-prod"
VAR3 = "another-var-prod"


  [[kv_namespaces]]
  id = "01962077d09242c5b0978a12bccaa5ed"
  binding = "KV"


[[durable_objects.bindings]]
name = "DO"
class_name = "Counter"
script_name = "testing"
