name = "pages-config-file"
pages_build_output_dir = "public"
compatibility_date = "2024-02-14"
compatibility_flags = ["url_standard"]

[env.preview]
compatibility_date = "2024-01-13"
compatibility_flags = ["no_url_standard"]


  [env.preview.vars]

  TEST_PLAINTEXT_PREVIEW = "PLAINTEXT"
  
VAR1 = "holiday-p"
VAR2 = "celebrate-p"
VAR3 = "another-var-p"

  [[env.preview.kv_namespaces]]
  id = "01962077d09242c5b0978a12bccaa5ed"
  binding = "KV_PREVIEW"

[[env.preview.durable_objects.bindings]]
name = "DO_PREVIEW"
class_name = "Counter"
script_name = "testing"

  [[env.preview.d1_databases]]
  database_id = "16678423-f19c-4a82-a3c1-161345dcfefe"
  binding = "D1_PREVIEW"
  database_name = "D1"

  [[env.preview.r2_buckets]]
  bucket_name = "images"
  binding = "R2_PREVIEW"

  [[env.preview.services]]
  binding = "SERVICE_PREVIEW"
  service = "no-bundle-import"
  environment = "production"

[[env.preview.queues.producers]]
binding = "Q_PREVIEW"
queue = "test"

  [[env.preview.analytics_engine_datasets]]
  binding = "AE_PREVIEW"
  dataset = "data"

  [env.preview.ai]
  binding = "AI_PREVIEW"

[env.production]
compatibility_date = "2024-02-13"
compatibility_flags = ["no_url_standard"]

  [env.production.vars]
  TEST_JSON = """
{
json: "value"
}"""
  TEST_PLAINTEXT = "PLAINTEXT"
  VAR1 = "holiday-prod"
VAR2 = "celebrate-prod"
VAR3 = "another-var-prod"

  [[env.production.kv_namespaces]]
  id = "01962077d09242c5b0978a12bccaa5ed"
  binding = "KV"

[[env.production.durable_objects.bindings]]
name = "DO"
class_name = "Counter"
script_name = "testing"

  [[env.production.d1_databases]]
  database_id = "16678423-f19c-4a82-a3c1-161345dcfefe"
  binding = "D1"
  database_name = "D1"

  [[env.production.r2_buckets]]
  bucket_name = "images"
  binding = "R2"

  [[env.production.services]]
  binding = "SERVICE"
  service = "no-bundle-import"
  environment = "production"

[[env.production.queues.producers]]
binding = "Q"
queue = "test"

  [[env.production.analytics_engine_datasets]]
  binding = "AE"
  dataset = "data"

  [env.production.ai]
  binding = "AI"
