pages_build_output_dir = "./mono-folder/public"
name = "pages-fns"
compatibility_date = "2024-01-01"

services = [
  { binding = "SERVICE", service = "no-bundle-worker" }
]

[vars]
DINOS = "dinosaures"
YARN_VERSION = "1"
