name = "pages-config-file"
compatibility_date = "2020-02-03"
pages_build_output_dir = "public"
[vars]
hello = "world"

[[durable_objects.bindings]]
name = "COUNTER"
class_name = "Counter"
script_name = "pages-config-do-test"
